name: Compile test ChimeraOS Linux Kernel

on:
    workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v3
      - name: Create build user
        run: |
          useradd -m build
          cp -vR linux /home/build/linux
          chown -vR build /home/build/linux
      - name: Set up pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          mkdir -p /etc/gnupg && echo "auto-key-retrieve" >> /etc/gnupg/gpg.conf
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm bc cpio pahole python kmod
      - name: Build linux-chimeraos package
        id: build-kernel-package
        shell: bash
        run: |
          su build bash -c "cd /home/build/linux && MAKEFLAGS=-j$(nproc) makepkg"
